//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CK.Plugin.Discoverer.Runner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class R {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal R() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CK.Plugin.Discoverer.Runner.R", typeof(R).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate the definition of the Dynamic Service (assembly not found)..
        /// </summary>
        internal static string AssemblyNotFoundForDynamicService {
            get {
                return ResourceManager.GetString("AssemblyNotFoundForDynamicService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} defines the same Configuration accessor as {1}..
        /// </summary>
        internal static string DuplicateEditConfigurationProperty {
            get {
                return ResourceManager.GetString("DuplicateEditConfigurationProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use of DynamicServiceAttribute requires a property that supports IDynamicService interface..
        /// </summary>
        internal static string DynamicServiceAttributeRequiresIDynamicService {
            get {
                return ResourceManager.GetString("DynamicServiceAttributeRequiresIDynamicService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic service other than Ck.Plugin.IService&lt;&gt; is not supported..
        /// </summary>
        internal static string GenericServiceOtherThanIServiceNotSupported {
            get {
                return ResourceManager.GetString("GenericServiceOtherThanIServiceNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implemented Service is on error..
        /// </summary>
        internal static string ImplementedServiceIsOnError {
            get {
                return ResourceManager.GetString("ImplementedServiceIsOnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A plugin can implement at most one IDynamicService..
        /// </summary>
        internal static string MultipleServiceImplementation {
            get {
                return ResourceManager.GetString("MultipleServiceImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service property is not writable (setter must be defined)..
        /// </summary>
        internal static string NotWritableServiceType {
            get {
                return ResourceManager.GetString("NotWritableServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A plugin must not implement any IService&lt;T&gt;: it must implement the T interface..
        /// </summary>
        internal static string PluginImplementIService {
            get {
                return ResourceManager.GetString("PluginImplementIService", resourceCulture);
            }
        }
    }
}
