//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CK.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class R {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal R() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CK.Core.R", typeof(R).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionSequence is read only: no action can be appended..
        /// </summary>
        internal static string ActionSequenceReadOnly {
            get {
                return ResourceManager.GetString("ActionSequenceReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ActivityLogger client is in NonRemoveableClients list..
        /// </summary>
        internal static string ActivityLoggerNonRemoveableClient {
            get {
                return ResourceManager.GetString("ActivityLoggerNonRemoveableClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument count can not be negative..
        /// </summary>
        internal static string ArgumentCountNegative {
            get {
                return ResourceManager.GetString("ArgumentCountNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} is direcly supported by the container. It can not be disabled..
        /// </summary>
        internal static string DirectServicesCanNotBeDisabled {
            get {
                return ResourceManager.GetString("DirectServicesCanNotBeDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occured while resolving type: {0}..
        /// </summary>
        internal static string ExceptionWhileResolvingType {
            get {
                return ResourceManager.GetString("ExceptionWhileResolvingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected attribute &apos;{0}&apos;..
        /// </summary>
        internal static string ExpectedXmlAttribute {
            get {
                return ResourceManager.GetString("ExpectedXmlAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected EndElement token named {0}..
        /// </summary>
        internal static string ExpectedXmlEndElement {
            get {
                return ResourceManager.GetString("ExpectedXmlEndElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not a valid assembly qualified name..
        /// </summary>
        internal static string InvalidAssemblyQualifiedName {
            get {
                return ResourceManager.GetString("InvalidAssemblyQualifiedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} is directly supported by the container..
        /// </summary>
        internal static string ServiceAlreadyDirectlySupported {
            get {
                return ResourceManager.GetString("ServiceAlreadyDirectlySupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} is already registered by the container..
        /// </summary>
        internal static string ServiceAlreadyRegistered {
            get {
                return ResourceManager.GetString("ServiceAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} is not implemented by object {1} returned by the callback..
        /// </summary>
        internal static string ServiceImplCallbackTypeMismatch {
            get {
                return ResourceManager.GetString("ServiceImplCallbackTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} is not implemented by object {1}..
        /// </summary>
        internal static string ServiceImplTypeMismatch {
            get {
                return ResourceManager.GetString("ServiceImplTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find service &apos;{0}&apos;..
        /// </summary>
        internal static string UnregisteredServiceInServiceProvider {
            get {
                return ResourceManager.GetString("UnregisteredServiceInServiceProvider", resourceCulture);
            }
        }
    }
}
