//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CK.Storage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class R {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal R() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CK.Storage.R", typeof(R).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type and object parameter can not be both null..
        /// </summary>
        internal static string AtLeastTypeOrObjectMustBeSpecified {
            get {
                return ResourceManager.GetString("AtLeastTypeOrObjectMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deserializing..
        /// </summary>
        internal static string DeserializeError {
            get {
                return ResourceManager.GetString("DeserializeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object reference &apos;{0}&apos; is already registered. An object can be deserialized only once..
        /// </summary>
        internal static string DuplicateReferenceObjectRegistration {
            get {
                return ResourceManager.GetString("DuplicateReferenceObjectRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimpleStructuredWriter.CloseFile must be used only with writer obtained by OpenFile..
        /// </summary>
        internal static string InvalidCallToSimpleStructuredWriterCloseFile {
            get {
                return ResourceManager.GetString("InvalidCallToSimpleStructuredWriterCloseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read file: manifest file can not be read..
        /// </summary>
        internal static string InvalidFileManifest {
            get {
                return ResourceManager.GetString("InvalidFileManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read file: version information is missing in manifest file..
        /// </summary>
        internal static string InvalidFileManifestVersion {
            get {
                return ResourceManager.GetString("InvalidFileManifestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while reading Xml..
        /// </summary>
        internal static string InvalidXml {
            get {
                return ResourceManager.GetString("InvalidXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing object reference attribute &apos;{0}&apos;..
        /// </summary>
        internal static string MissingReferenceAttribute {
            get {
                return ResourceManager.GetString("MissingReferenceAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to use structured serialization. The object does not implement IStructuredSerializable and no IStructuredSerializer service exists for the type {0}..
        /// </summary>
        internal static string NotWritableStructuredObject {
            get {
                return ResourceManager.GetString("NotWritableStructuredObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect binary data. Size differ. Expected {0}, was {1}..
        /// </summary>
        internal static string SizeDifferError {
            get {
                return ResourceManager.GetString("SizeDifferError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read inline object from Xml..
        /// </summary>
        internal static string UnableToReadInlineObject {
            get {
                return ResourceManager.GetString("UnableToReadInlineObject", resourceCulture);
            }
        }
    }
}
