xcopy ..\..\CK.Core\bin\Debug ..\Runtime\Debug\ /y
xcopy ..\..\CK.Context\bin\Debug ..\Runtime\Debug\ /y
xcopy ..\..\CK.Interop\bin\Debug ..\Runtime\Debug\ /y
xcopy ..\..\CK.Keyboard\bin\Debug ..\Runtime\Debug\ /y
xcopy ..\..\CK.Keyboard.Model\bin\Debug ..\Runtime\Debug\ /y
xcopy ..\..\CK.Plugin.Config\bin\Debug ..\Runtime\Debug\ /y
xcopy ..\..\CK.Plugin.Config.Model\bin\Debug ..\Runtime\Debug\ /y
xcopy ..\..\CK.Plugin.Discoverer\bin\Debug ..\Runtime\Debug\ /y
xcopy ..\..\CK.Plugin.Discoverer.Runner\bin\Debug ..\Runtime\Debug\ /y
xcopy ..\..\CK.Plugin.Host\bin\Debug ..\Runtime\Debug\ /y
xcopy ..\..\CK.Plugin.Host.Tests\bin\Debug ..\Runtime\Debug\ /y
xcopy ..\..\CK.Plugin.Model\bin\Debug ..\Runtime\Debug\ /y
xcopy ..\..\CK.Plugin.Runner\bin\Debug ..\Runtime\Debug\ /y
xcopy ..\..\CK.Reflection\bin\Debug ..\Runtime\Debug\ /y
xcopy ..\..\CK.SharedDic\bin\Debug ..\Runtime\Debug\ /y
xcopy ..\..\CK.Storage\bin\Debug ..\Runtime\Debug\ /y
